M48
; DRILL file KiCad 10.0.0 date 2026-04-01T12:28:36
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-04-01T12:28:36-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0984
%
G90
G05
T1
X1.6535Y-1.437
X1.6535Y-3.6024
X4.5276Y-1.437
X4.5276Y-3.6024
M30
